### ISSUE TITLE
去除多余的css，好像并没有效果

### ISSUE THREAD

**Issue by 41152419901017** [staven630/vue-cli4-config#1]
我把项目下下来之后，home.vue添加了无用的一个css,结果打包出来还在

**Comment by 41152419901017** [comment]
有时间帮忙看下哦

**Comment by 41152419901017** [comment]
css和html都在.vue里没分开， 导致无用css无法消除。 分开的话，可以。有啥方法没

**Comment by staven630** [comment]
十分抱歉，针对这种情况，我试过其他几种方法，如：@fullhuman/postcss-purgecss也没能解决。目前还没有什么好的解决办法。按需引入elementui，可能还会导致许多样式丢失了。这项功能还望斟酌具体情况选择要不要使用……[purgecss](https://github.com/FullHuman/purgecss/issues)

**Comment by chen-can** [comment]
vue cli3 无法使用

**Comment by anthinkingcoder** [comment]
他这个是因为是用正则(/[A-Za-z0-9-_:/]+/g)去匹配.vue文件除了style标签内的所有文本所满足条件的，
满足则不去除，例如 你有个.ab {}样式，如果代码里有const temp = {d: 'ab'}, 这样会匹配到ab 所以.ab样式没有被去除的。
