### ISSUE TITLE
runtimeCompiler这个配置是不是可以去掉

### ISSUE THREAD

**Issue by sunxingchen1995** [staven630/vue-cli4-config#2]
在官方文档中写了，用了vue-loader的话，没必要使用运行时编译的版本了，会加大打包体积，是不是可以去掉这个配置呢？详见下图：

![image](https://user-images.githubusercontent.com/30208434/53145295-9aeee180-35da-11e9-8005-eac3c011fdbe.png)

**Comment by staven630** [comment]
那貌似需要手动配置vue-loader

**Comment by sunxingchen1995** [comment]
不用的，vue-loader是vue-cli用来编译.vue文件的，自带的依赖，设置成fasle试一下就知道啦

**Comment by staven630** [comment]
> 不用的，vue-loader是vue-cli用来编译.vue文件的，自带的依赖，设置成fasle试一下就知道啦

好的，回头我试下
