### ISSUE TITLE
https://www.v2ex.com/t/654428

### ISSUE THREAD

**Issue by jianrry** [staven630/vue-cli4-config#30]
https://www.v2ex.com/t/654428

老哥,这篇文章是你发的吗?或者有没有你的授权?

这篇文章没有表明转载,署名的作者也不是你,连你的项目地址的懒得放.

还不忘记在文章的末尾放上自己的公众号 GitHub 语雀 网站进行推广.

这样的行为我有点看不下去了,发一条issue提醒一下

**Comment by staven630** [comment]
是我原创的

**Comment by staven630** [comment]
运营公众号，不坚持原创。未经授权，直接转载剽窃。的确有点恶心！
