### ISSUE TITLE
run build --watch 问题

### ISSUE THREAD

**Issue by WuYunlong** [staven630/vue-cli4-config#66]
现在我使用 `@vue/cli 4.5.13` 创建项目因为业务需求要实时进行编译。
使用如下命令 `yarn run build --watch` 但是现在遇到如下问题。
就是在每次重新编译的时候我需要往一个文件里面写入一个字符串
```javascript
fs.appendFileSync('./build.log', `${new Date()}\n`,() => {
    console.log('写入成功')
})
```
这个要如何进行配置 在每次重新build的时候执行

**Comment by zuolg** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
